# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a648f7bc1e76f3fb2a7ff62dfac299a9312be149953d150e6b7323eb1bc4c27eeb50e3be6c41fa9f01b9527a0ad3c5c388ee5facffcf35f776bb9509c10e4a76

test:
  secret_key_base: 3e80b07234d793616883b1f67dadf6b6e6e00fd90e95645b4c9557a18a71eb8ca5c4fd540f2509d5f058b982b4139404f2a56afaccf82cc8e80dee787afca5d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
